package dgt;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author amora
 */
public class Pantalla_Funcionario extends javax.swing.JFrame {

    private SEstatal sistema;

    public Pantalla_Funcionario(Usuario usuario, SEstatal se) {
        initComponents();
        this.PanelAltaUsuario.setVisible(false);
        this.sistema = se;
        this.establecerSaludo();
        this.LabelNombreUsuario.setText(usuario.getNombre() + " " + usuario.getApellidos());
        this.jLabel5.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelConfirmacionAltaUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        PanelInicioFuncionario = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        BotonAltaUsuario = new javax.swing.JButton();
        BotonRevisarAlegaciones = new javax.swing.JButton();
        BotonBuscarUsuario = new javax.swing.JButton();
        BotonAltaVehiculo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PanelSaludo = new javax.swing.JPanel();
        LabelTiempo = new javax.swing.JLabel();
        LabelNombreUsuario = new javax.swing.JLabel();
        LabelQueDeseaHacer = new javax.swing.JLabel();
        PanelAltaUsuario = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        PanelTipoUsuario = new javax.swing.JPanel();
        LabelTipoUsuario = new javax.swing.JLabel();
        BotonAltaConductor = new javax.swing.JToggleButton();
        BotonAltaAgente = new javax.swing.JToggleButton();
        BotonAltaFuncionario = new javax.swing.JToggleButton();
        PanelDatos = new javax.swing.JPanel();
        LabelTextoNombre = new javax.swing.JLabel();
        CampoNombre = new javax.swing.JTextField();
        LabelTextoApellidos = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        LabelTextoDireccion = new javax.swing.JLabel();
        CampoDireccion = new javax.swing.JTextField();
        LabelTextoEmail = new javax.swing.JLabel();
        CampoEmail = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanel1 = new javax.swing.JPanel();
        PanelDatosConductor = new javax.swing.JPanel();
        Textonumero = new javax.swing.JLabel();
        CampoNumeroCarnet = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        CampoFechaExpiracion = new org.jdesktop.swingx.JXDatePicker();
        TextoFechaExpiracion = new javax.swing.JLabel();
        TextoFechaExpedicion = new javax.swing.JLabel();
        CampoFechaExpedicion = new org.jdesktop.swingx.JXDatePicker();
        CheckboxGafas = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BotonAnadirUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CampoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoContraseña = new javax.swing.JTextField();

        PanelConfirmacionAltaUsuario.setBackground(new java.awt.Color(204, 204, 255));
        PanelConfirmacionAltaUsuario.setPreferredSize(new java.awt.Dimension(448, 200));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESULTADO");

        jButton2.setText("CONTINUAR");

        javax.swing.GroupLayout PanelConfirmacionAltaUsuarioLayout = new javax.swing.GroupLayout(PanelConfirmacionAltaUsuario);
        PanelConfirmacionAltaUsuario.setLayout(PanelConfirmacionAltaUsuarioLayout);
        PanelConfirmacionAltaUsuarioLayout.setHorizontalGroup(
            PanelConfirmacionAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfirmacionAltaUsuarioLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(PanelConfirmacionAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        PanelConfirmacionAltaUsuarioLayout.setVerticalGroup(
            PanelConfirmacionAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelConfirmacionAltaUsuarioLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(225, 231, 243));
        setPreferredSize(new java.awt.Dimension(700, 500));

        PanelInicioFuncionario.setBackground(new java.awt.Color(225, 231, 243));

        PanelBotones.setBackground(new java.awt.Color(225, 231, 243));

        BotonAltaUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonAltaUsuario.setText("Alta usuario");
        BotonAltaUsuario.setPreferredSize(new java.awt.Dimension(200, 100));
        BotonAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaUsuarioActionPerformed(evt);
            }
        });

        BotonRevisarAlegaciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonRevisarAlegaciones.setText("Revisar alegaciones");
        BotonRevisarAlegaciones.setPreferredSize(new java.awt.Dimension(200, 100));
        BotonRevisarAlegaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRevisarAlegacionesActionPerformed(evt);
            }
        });

        BotonBuscarUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonBuscarUsuario.setText("Buscar usuario");
        BotonBuscarUsuario.setPreferredSize(new java.awt.Dimension(200, 100));
        BotonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarUsuarioActionPerformed(evt);
            }
        });

        BotonAltaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonAltaVehiculo.setText("Alta vehículo");
        BotonAltaVehiculo.setPreferredSize(new java.awt.Dimension(200, 100));
        BotonAltaVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaVehiculoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Baja vehículo");
        jButton1.setPreferredSize(new java.awt.Dimension(200, 100));

        PanelSaludo.setBackground(new java.awt.Color(225, 231, 243));

        LabelTiempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTiempo.setText("Saludo");

        LabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelNombreUsuario.setText("Nombre");

        LabelQueDeseaHacer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelQueDeseaHacer.setText("¿Que desea hacer?");

        javax.swing.GroupLayout PanelSaludoLayout = new javax.swing.GroupLayout(PanelSaludo);
        PanelSaludo.setLayout(PanelSaludoLayout);
        PanelSaludoLayout.setHorizontalGroup(
            PanelSaludoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaludoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSaludoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSaludoLayout.createSequentialGroup()
                        .addComponent(LabelTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelNombreUsuario))
                    .addComponent(LabelQueDeseaHacer))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSaludoLayout.setVerticalGroup(
            PanelSaludoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSaludoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSaludoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTiempo)
                    .addComponent(LabelNombreUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelQueDeseaHacer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBotonesLayout.createSequentialGroup()
                        .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelBotonesLayout.createSequentialGroup()
                                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonRevisarAlegaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonBuscarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BotonAltaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBotonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PanelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addComponent(PanelSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRevisarAlegaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAltaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelInicioFuncionarioLayout = new javax.swing.GroupLayout(PanelInicioFuncionario);
        PanelInicioFuncionario.setLayout(PanelInicioFuncionarioLayout);
        PanelInicioFuncionarioLayout.setHorizontalGroup(
            PanelInicioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioFuncionarioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInicioFuncionarioLayout.setVerticalGroup(
            PanelInicioFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioFuncionarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelAltaUsuario.setBackground(new java.awt.Color(225, 231, 243));
        PanelAltaUsuario.setPreferredSize(new java.awt.Dimension(700, 550));

        LabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelTitulo.setText("ALTA USUARIO");

        PanelTipoUsuario.setBackground(new java.awt.Color(225, 231, 243));
        PanelTipoUsuario.setPreferredSize(new java.awt.Dimension(322, 72));

        LabelTipoUsuario.setText("Tipo de usuario:");

        BotonAltaConductor.setText("Conductor");
        BotonAltaConductor.setPreferredSize(new java.awt.Dimension(100, 30));
        BotonAltaConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaConductorActionPerformed(evt);
            }
        });

        BotonAltaAgente.setText("Agente");
        BotonAltaAgente.setPreferredSize(new java.awt.Dimension(100, 30));
        BotonAltaAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaAgenteActionPerformed(evt);
            }
        });

        BotonAltaFuncionario.setText("Funcionario");
        BotonAltaFuncionario.setPreferredSize(new java.awt.Dimension(100, 30));
        BotonAltaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAltaFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTipoUsuarioLayout = new javax.swing.GroupLayout(PanelTipoUsuario);
        PanelTipoUsuario.setLayout(PanelTipoUsuarioLayout);
        PanelTipoUsuarioLayout.setHorizontalGroup(
            PanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoUsuarioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(PanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTipoUsuario)
                    .addGroup(PanelTipoUsuarioLayout.createSequentialGroup()
                        .addComponent(BotonAltaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAltaAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonAltaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTipoUsuarioLayout.setVerticalGroup(
            PanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTipoUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTipoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelTipoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonAltaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAltaAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonAltaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelDatos.setBackground(new java.awt.Color(225, 231, 243));

        LabelTextoNombre.setText("Nombre:");

        CampoNombre.setPreferredSize(new java.awt.Dimension(150, 20));

        LabelTextoApellidos.setText("Apellidos:");

        CampoApellidos.setPreferredSize(new java.awt.Dimension(150, 20));

        LabelTextoDireccion.setText("Dirección:");

        CampoDireccion.setPreferredSize(new java.awt.Dimension(150, 20));

        LabelTextoEmail.setText("Email:");

        CampoEmail.setMaximumSize(new java.awt.Dimension(200, 20));
        CampoEmail.setMinimumSize(new java.awt.Dimension(150, 20));
        CampoEmail.setPreferredSize(new java.awt.Dimension(150, 20));

        jPanel1.setBackground(new java.awt.Color(225, 231, 243));

        PanelDatosConductor.setBackground(new java.awt.Color(225, 231, 243));

        Textonumero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Textonumero.setText("Numero de carnet:");
        Textonumero.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        CampoNumeroCarnet.setMinimumSize(new java.awt.Dimension(150, 20));
        CampoNumeroCarnet.setPreferredSize(new java.awt.Dimension(150, 20));

        jPanel2.setBackground(new java.awt.Color(225, 231, 243));

        TextoFechaExpiracion.setText("Fecha de expiración:");

        TextoFechaExpedicion.setText("Fecha de expedición:");

        CheckboxGafas.setBackground(new java.awt.Color(225, 231, 243));
        CheckboxGafas.setText("Tiene que llevar gafas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextoFechaExpedicion)
                            .addComponent(CampoFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextoFechaExpiracion)))
                    .addComponent(CheckboxGafas))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoFechaExpedicion)
                    .addComponent(TextoFechaExpiracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoFechaExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoFechaExpedicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckboxGafas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelDatosConductorLayout = new javax.swing.GroupLayout(PanelDatosConductor);
        PanelDatosConductor.setLayout(PanelDatosConductorLayout);
        PanelDatosConductorLayout.setHorizontalGroup(
            PanelDatosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosConductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Textonumero)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoNumeroCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        PanelDatosConductorLayout.setVerticalGroup(
            PanelDatosConductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosConductorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Textonumero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoNumeroCarnet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(225, 231, 243));

        jLabel4.setText("Provincia:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A Coruña", "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila", "Badajoz", "Islas Baleares", "Barcelona", "Burgos", "Cáceres", "Cádiz", "Cantabria", "Castellón", "Ciudad Real", "Córdoba", "Cuenca", "Girona", "Granada", "Guadalajara", "Guipúzcoa", "Huelva", "Huesca", "Jaén", "La Rioja", "Las Palmas", "León", "Lleida", "Lugo", "Madrid", "Málaga", "Murcia", "Navarra", "Orense", "Palencia", "Pontevedra", "Salamanca", "Segovia", "Sevilla", "Soria", "Tarragona", "Santa Cruz de Tenerife", "Teruel", "Toledo", "Valencia", "Valladolid", "Vizcaya", "Zamora", "Zaragoza", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(0, 104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BotonAnadirUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonAnadirUsuario.setText("DAR DE ALTA");
        BotonAnadirUsuario.setPreferredSize(new java.awt.Dimension(150, 50));
        BotonAnadirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnadirUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelDatosConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonAnadirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonAnadirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre de usuario:");

        CampoUsuario.setPreferredSize(new java.awt.Dimension(150, 20));

        jLabel3.setText("Contraseña:");

        CampoContraseña.setMinimumSize(new java.awt.Dimension(0, 0));
        CampoContraseña.setPreferredSize(new java.awt.Dimension(150, 20));

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LabelTextoApellidos)
                                .addComponent(CampoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelTextoNombre)
                                .addComponent(LabelTextoDireccion)
                                .addComponent(CampoDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CampoEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelTextoEmail))
                            .addComponent(jLabel2)
                            .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(LabelTextoNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTextoApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTextoDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelTextoEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAltaUsuarioLayout = new javax.swing.GroupLayout(PanelAltaUsuario);
        PanelAltaUsuario.setLayout(PanelAltaUsuarioLayout);
        PanelAltaUsuarioLayout.setHorizontalGroup(
            PanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTitulo)
                    .addComponent(PanelTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelAltaUsuarioLayout.setVerticalGroup(
            PanelAltaUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAltaUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAltaUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelInicioFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelAltaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 505, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(PanelInicioFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 36, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaUsuarioActionPerformed
        this.PanelInicioFuncionario.setVisible(false);
        this.PanelConfirmacionAltaUsuario.setVisible(false);
        this.PanelAltaUsuario.setVisible(true);

    }//GEN-LAST:event_BotonAltaUsuarioActionPerformed

    private void BotonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonBuscarUsuarioActionPerformed

    private void BotonRevisarAlegacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRevisarAlegacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRevisarAlegacionesActionPerformed

    private void BotonAltaVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonAltaVehiculoActionPerformed

    private void BotonAltaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaFuncionarioActionPerformed
        this.BotonAltaConductor.setSelected(false);
        this.BotonAltaAgente.setSelected(false);
        this.modificarAltaFuncionario();
    }//GEN-LAST:event_BotonAltaFuncionarioActionPerformed

    private void BotonAltaAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaAgenteActionPerformed
        this.BotonAltaConductor.setSelected(false);
        this.BotonAltaFuncionario.setSelected(false);
        this.modificarAltaAgente();
    }//GEN-LAST:event_BotonAltaAgenteActionPerformed

    private void BotonAltaConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAltaConductorActionPerformed
        this.BotonAltaAgente.setSelected(false);
        this.BotonAltaFuncionario.setSelected(false);
        this.modificarAltaConductor();
    }//GEN-LAST:event_BotonAltaConductorActionPerformed

    private void BotonAnadirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnadirUsuarioActionPerformed
        this.jLabel5.setText("Hecho");
        if (this.BotonAltaConductor.isSelected()) {

            Carnet nuevocarnet = new Carnet(LocalDate.of(this.CampoFechaExpedicion.getDate().getYear(), this.CampoFechaExpedicion.getDate().getMonth(), this.CampoFechaExpedicion.getDate().getDate()), LocalDate.of(this.CampoFechaExpiracion.getDate().getYear(), this.CampoFechaExpiracion.getDate().getMonth(), this.CampoFechaExpiracion.getDate().getDate()), this.CheckboxGafas.isSelected(), this.CampoNumeroCarnet.getText());
            Conductor nuevoconductor;
            nuevoconductor = new Conductor(nuevocarnet, this.CampoUsuario.getText(), this.CampoContraseña.getText(), this.jComboBox1.getSelectedItem().toString(), this.CampoNombre.getText(), this.CampoApellidos.getText(), this.CampoDireccion.getText(), this.CampoEmail.getText());
            this.sistema.addConductorADGT(this.jComboBox1.getSelectedItem().toString(), nuevoconductor);
        }
        if (this.BotonAltaFuncionario.isSelected()) {
            Funcionario nuevofuncionario;
            nuevofuncionario = new Funcionario(Integer.parseInt(this.CampoNumeroCarnet.getText()), this.CampoUsuario.getText(), this.CampoContraseña.getText(), this.jComboBox1.getSelectedItem().toString(), this.CampoNombre.getText(), this.CampoApellidos.getText(), this.CampoDireccion.getText(), this.CampoEmail.getText());
            this.sistema.addFuncionarioADGT(this.jComboBox1.getSelectedItem().toString(), nuevofuncionario);
        }
        if (this.BotonAltaAgente.isSelected()) {
            Agente nuevoagente;
            nuevoagente = new Agente(Integer.parseInt(this.CampoNumeroCarnet.getText()), this.CampoUsuario.getText(), this.CampoContraseña.getText(), this.jComboBox1.getSelectedItem().toString(), this.CampoNombre.getText(), this.CampoApellidos.getText(), this.CampoDireccion.getText(), this.CampoEmail.getText());
            this.sistema.addAgenteADGT(this.jComboBox1.getSelectedItem().toString(), nuevoagente);
        }

        try {
            this.esperar(3000);
        } catch (InterruptedException ex) {
            Logger.getLogger(Pantalla_Funcionario.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.PanelInicioFuncionario.setVisible(true);
        this.PanelAltaUsuario.setVisible(false);
        this.BotonAnadirUsuario.setText("DAR DE ALTA");

    }//GEN-LAST:event_BotonAnadirUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Funcionario(Pantalla_Login.getUsuario(), Pantalla_Login.getSistema()).setVisible(true);
            }
        });
    }

    public void modificarAltaConductor() {
        this.Textonumero.setText("Numero de carnet");
        this.jPanel2.setVisible(true);
    }

    public void modificarAltaAgente() {
        this.Textonumero.setText("Identificación:");
        this.jPanel2.setVisible(false);
    }

    public void modificarAltaFuncionario() {
        this.Textonumero.setText("Identificación:");
        this.jPanel2.setVisible(false);
    }

    private void establecerSaludo() {
        if ((LocalTime.now().getHour() >= 8) && (LocalTime.now().getHour() < 17)) {
            this.LabelTiempo.setText("Buenos dias");
        } else {
            if ((LocalTime.now().getHour() >= 17) && (LocalTime.now().getHour() < 21)) {
                this.LabelTiempo.setText("Buenas tardes");
            } else {
                this.LabelTiempo.setText("Buenas noches");
            }
        }
    }

    private void esperar(int milis) throws InterruptedException {
        Thread.sleep(milis);
    }

    private void confirmar() {
        this.jLabel5.setText("Hecho");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAltaAgente;
    private javax.swing.JToggleButton BotonAltaConductor;
    private javax.swing.JToggleButton BotonAltaFuncionario;
    private javax.swing.JButton BotonAltaUsuario;
    private javax.swing.JButton BotonAltaVehiculo;
    private javax.swing.JButton BotonAnadirUsuario;
    private javax.swing.JButton BotonBuscarUsuario;
    private javax.swing.JButton BotonRevisarAlegaciones;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoContraseña;
    private javax.swing.JTextField CampoDireccion;
    private javax.swing.JTextField CampoEmail;
    private org.jdesktop.swingx.JXDatePicker CampoFechaExpedicion;
    private org.jdesktop.swingx.JXDatePicker CampoFechaExpiracion;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JTextField CampoNumeroCarnet;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JCheckBox CheckboxGafas;
    private javax.swing.JLabel LabelNombreUsuario;
    private javax.swing.JLabel LabelQueDeseaHacer;
    private javax.swing.JLabel LabelTextoApellidos;
    private javax.swing.JLabel LabelTextoDireccion;
    private javax.swing.JLabel LabelTextoEmail;
    private javax.swing.JLabel LabelTextoNombre;
    private javax.swing.JLabel LabelTiempo;
    private javax.swing.JLabel LabelTipoUsuario;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JPanel PanelAltaUsuario;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelConfirmacionAltaUsuario;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelDatosConductor;
    private javax.swing.JPanel PanelInicioFuncionario;
    private javax.swing.JPanel PanelSaludo;
    private javax.swing.JPanel PanelTipoUsuario;
    private javax.swing.JLabel TextoFechaExpedicion;
    private javax.swing.JLabel TextoFechaExpiracion;
    private javax.swing.JLabel Textonumero;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
